---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: external-secretstore
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-sa